### PR TITLE
Status API draft (needs discussion), ANT build file, smaller issues

### PR DESCRIPTION
**Pull request by mstrap**

### CODE REVIEW

**Comment by ethomson** [comment]
So I'm afraid that I've accidentally stepped on your toes a bit.  Yesterday I got a new Java dev environment set up on my new computer, and I set up CI builds for AppVeyor.  As a result, I noticed a couple of the same issues that you have fixed here.  For example:  the issues with SAL annotations when using VS 2015 and having the Windows 10 SDK installed.  Apologies for that.

I'm going to cherry-pick a couple of these other commits to get them merged into master, since most of them seem very reasonable and because I think that the status API will require some iteration and discussion and that shouldn't hold up (for example) some of the `make.cmd` changes.

**Comment by ethomson** [comment]
I cherry-picked many of your commits.  Aside from the status commit, I did *not* include the following commits:

`d631bcf`:  You're adding `.idea` to `.gitignore` and also checking the folder in.  Is this intentional?  Why would we not ignore it wholesale?
`39db6db`: Why ant and not maven?  Do we really need both?  Do we really need to check in junit?

It might be easier in the future if you created more narrowly scoped pull requests so that they can be included independently of each other.  Thanks!

**Comment by ethomson** [comment]
Oh, finally, a note on status.  It probably makes more sense to use `git_status_list_new` instead of `git_status_foreach`.  That's the more modern API and should hopefully be much easier to bind to Java.  That way you can create a `Status` class that contains the statuses instead of the callback pattern.

**Comment by mstrap** [comment]
> d631bcf: You're adding .idea to .gitignore and also checking the folder in. Is this intentional?
> Why would we not ignore it wholesale?

I've added those files of IDEA's configuration which are installation-independent and sufficient to start working with IDEA. All other files from the configuration area should be ignored.

> 39db6db: Why ant and not maven? Do we really need both? Do we really need to check in junit?

You are right, we shouldn't run both. I'll try to extend the Maven configuration for the native build part (which was the reason why I've introduced the ANT file). junit.jar is just necessary for ANT.

> Oh, finally, a note on status. It probably makes more sense to use git_status_list_new instead of
> git_status_foreach. That's the more modern API and should hopefully be much easier to bind to Java.

Will do. Actually, I was already considering this as alternative to `git_status_foreach` because I was expecting the Java callback to significantly impact performance. Fortunately, it didn't.

What do you think of the JNI utility macros? Should existing code be improved, too? I'm no pre-processor expert and I'm not sure whether the duplication for `void`-methods vs. `return NULL` could be improved. My goal was to shorten the "trivial" code parts. Maybe there is an even better solution for that?

Regarding the libgit2 API, I haven't figured out yet whether I can perform a non-recursive directory status (though my suspect is that I can't). [Here](http://stackoverflow.com/questions/35582759) is my related StackOverflow question.

**Pull request closed without merging**
